#include <iostream>
using namespace std; 
int main(void) {
    uint64_t i;
    uint64_t iter = 1000000;
    for (i=0; i < iter; i++) {
        __asm__ (
                "clc\n"
                "clc\n"
                "mov $10, %eax\n"
                "cmp $15, %eax\n"
                "jle l780\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l780: jle l781\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l781: jle l782\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l782: jle l783\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l783: jle l784\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l784: jle l785\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l785: jle l786\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l786: jle l787\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l787: jle l788\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l788: jle l789\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l789: jle l78a\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l78a: jle l78b\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l78b: jle l78c\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l78c: jle l78d\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l78d: jle l78e\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l78e: jle l78f\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l78f: jle l790\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l790: jle l791\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l791: jle l792\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l792: jle l793\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l793: jle l794\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l794: jle l795\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l795: jle l796\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l796: jle l797\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l797: jle l798\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l798: jle l799\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l799: jle l79a\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l79a: jle l79b\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l79b: jle l79c\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l79c: jle l79d\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l79d: jle l79e\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l79e: jle l79f\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l79f: jle l7a0\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a0: jle l7a1\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a1: jle l7a2\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a2: jle l7a3\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a3: jle l7a4\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a4: jle l7a5\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a5: jle l7a6\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a6: jle l7a7\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a7: jle l7a8\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a8: jle l7a9\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7a9: jle l7aa\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7aa: jle l7ab\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7ab: jle l7ac\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7ac: jle l7ad\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7ad: jle l7ae\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7ae: jle l7af\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7af: jle l7b0\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b0: jle l7b1\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b1: jle l7b2\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b2: jle l7b3\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b3: jle l7b4\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b4: jle l7b5\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b5: jle l7b6\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b6: jle l7b7\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b7: jle l7b8\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b8: jle l7b9\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7b9: jle l7ba\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7ba: jle l7bb\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7bb: jle l7bc\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7bc: jle l7bd\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7bd: jle l7be\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7be: jle l7bf\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7bf: jle l7c0\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c0: jle l7c1\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c1: jle l7c2\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c2: jle l7c3\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c3: jle l7c4\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c4: jle l7c5\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c5: jle l7c6\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c6: jle l7c7\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c7: jle l7c8\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c8: jle l7c9\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7c9: jle l7ca\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7ca: jle l7cb\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7cb: jle l7cc\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7cc: jle l7cd\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7cd: jle l7ce\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7ce: jle l7cf\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7cf: jle l7d0\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d0: jle l7d1\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d1: jle l7d2\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d2: jle l7d3\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d3: jle l7d4\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d4: jle l7d5\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d5: jle l7d6\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d6: jle l7d7\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d7: jle l7d8\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d8: jle l7d9\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7d9: jle l7da\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7da: jle l7db\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7db: jle l7dc\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7dc: jle l7dd\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7dd: jle l7de\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7de: jle l7df\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7df: jle l7e0\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7e0: jle l7e1\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7e1: jle l7e2\n"
                "clc\n"
                "clc\n"
                "clc\n"
                "l7e2: clc\n"
                );
    }
}
